version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/app
      - /app/node_modules

    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      PORT: 5173
    depends_on:
      - backend
    networks:
      - gux-net

  backend:
    depends_on:
      - db
    build:
      context: ./backend
      target: base
      dockerfile: Dockerfile
    container_name: backend

    volumes:
      -  ./backend:/app
      - /app/node_modules

    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - gux-net

  db:
    image: postgres
    container_name: postgres
    networks:
      - gux-net

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false

networks:
  gux-net: